// app.js — the interactive, beginner-friendly form. Renders controls from the
// schema, keeps a single `state` object, persists it (localStorage + share
// link + downloadable project file) and shows a live preview generated by
// generate.js.
import {
  POWERMETERS,
  getPowermeter,
  PHASE_CAPABLE,
  DEVICE_TYPES,
  PER_METER_TUNING,
  CT_BASIC,
  CT_ACTIVE,
  CT_BALANCER,
  CT_EFFICIENCY,
  CT_SATURATION,
  MARSTEK_FIELDS,
  MQTT_INSIGHTS_FIELDS,
  ESP_BOARDS,
  HARDWARE,
  type Field,
  type Powermeter,
} from "./schema.js";
import { generate } from "./generate.js";
import { ghDoc } from "./links.js";
import { STORAGE_KEY, newMeter, defaultState, safeParse, migrate, type State, type Meter } from "./state.js";

let state: State = loadState() || defaultState();

// ── tiny DOM helper ─────────────────────────────────────────────────────────
type ElProps = Record<string, any>;
type ElChild = Node | string | null | undefined;
function el<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  props?: ElProps,
  children?: ElChild | ElChild[],
): HTMLElementTagNameMap[K];
function el(tag: string, props: ElProps = {}, children: ElChild | ElChild[] = []): HTMLElement {
  const node = document.createElement(tag);
  for (const [k, v] of Object.entries(props)) {
    if (k === "class") node.className = v;
    else if (k === "html") node.innerHTML = v;
    else if (k === "text") node.textContent = v;
    else if (k.startsWith("on") && typeof v === "function") node.addEventListener(k.slice(2), v as EventListener);
    else if (v === true) node.setAttribute(k, "");
    else if (v !== false && v != null) node.setAttribute(k, String(v));
  }
  const kids = Array.isArray(children) ? children : [children];
  for (const c of kids) {
    if (c == null) continue;
    node.appendChild(typeof c === "string" ? document.createTextNode(c) : c);
  }
  return node;
}

// ── generic field renderer ───────────────────────────────────────────────────
// Renders one schema field bound to obj[field.key]. `phases` controls phase
// expansion. Calls refreshPreview() on change; if field.structural, also calls
// rerenderAll() so dependent sections appear/disappear.
function fieldControl(
  field: Field,
  obj: Record<string, any>,
  { phases = 1, structural = false }: { phases?: number; structural?: boolean } = {},
): HTMLElement {
  const help = field.help ? el("p", { class: "help", text: field.help }) : null;
  const labelText = field.label + (field.required ? " *" : "");

  // phase-aware text fields → three L1/L2/L3 boxes joined with ", "
  if (field.phase && phases === 3 && (field.type === "text" || field.type === "number")) {
    const parts = String(obj[field.key] || "").split(",").map((s) => s.trim());
    while (parts.length < 3) parts.push("");
    const boxes = ["L1", "L2", "L3"].map((ph, i) => {
      const inp = el("input", {
        type: field.type,
        value: parts[i] || "",
        placeholder: ph,
        "aria-label": `${field.label} ${ph}`,
      });
      inp.addEventListener("input", () => {
        parts[i] = inp.value.trim();
        obj[field.key] = joinPhases(parts);
        refreshPreview();
      });
      return inp;
    });
    return el("div", { class: "field" }, [
      el("label", { text: labelText, class: "field-label" }),
      el("div", { class: "phase-row" }, boxes),
      help,
    ]);
  }

  let control: HTMLInputElement | HTMLSelectElement;
  if (field.type === "select") {
    control = el(
      "select",
      {},
      (field.options ?? []).map((o) =>
        el("option", { value: o.value, ...(String(obj[field.key] ?? field.default ?? "") === o.value ? { selected: true } : {}) }, o.label),
      ),
    );
    if (obj[field.key] === undefined && field.default !== undefined) obj[field.key] = field.default;
    control.addEventListener("change", () => {
      obj[field.key] = control.value;
      if (structural) rerenderAll();
      else refreshPreview();
    });
  } else if (field.type === "checkbox") {
    if (obj[field.key] === undefined) obj[field.key] = !!field.default;
    const cb = el("input", { type: "checkbox", ...(obj[field.key] ? { checked: true } : {}) });
    cb.addEventListener("change", () => {
      obj[field.key] = cb.checked;
      if (structural) rerenderAll();
      else refreshPreview();
    });
    return el("div", { class: "field field-check" }, [
      el("label", { class: "check-label" }, [cb, el("span", { text: labelText })]),
      help,
    ]);
  } else {
    control = el("input", {
      type: field.type,
      value: obj[field.key] ?? "",
      placeholder: field.placeholder || "",
    });
    if (field.type === "password") control.classList.add("secret");
    control.addEventListener("input", () => {
      obj[field.key] = control.value;
      refreshPreview();
    });
  }

  return el("div", { class: "field" }, [el("label", { text: labelText, class: "field-label" }), control, help]);
}

// HTML-escape a (possibly untrusted, restored) value before it goes into an
// innerHTML string. Used for state values interpolated into `html:` props.
function escapeHtml(v: unknown): string {
  return String(v ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function linkOut(href: string, text: string): HTMLElement {
  return el("a", { href, target: "_blank", rel: "noopener", class: "btn-link" }, text + " ↗");
}

function joinPhases(parts: string[]): string {
  // keep up to the last non-empty entry so "a,,c" round-trips
  let last = -1;
  parts.forEach((p, i) => {
    if (p !== "") last = i;
  });
  if (last < 0) return "";
  return parts.slice(0, last + 1).join(", ");
}

// group a list of fields, splitting advanced ones into a <details>
function fieldGroup(fields: Field[], obj: Record<string, any>, ctx: { phases?: number; structural?: boolean } = {}): HTMLElement[] {
  const basic = fields.filter((f) => !f.advanced);
  const advanced = fields.filter((f) => f.advanced);
  const nodes = basic.map((f) => fieldControl(f, obj, ctx));
  if (advanced.length) {
    nodes.push(
      el("details", { class: "adv" }, [
        el("summary", { text: "Advanced options" }),
        el("div", { class: "field-grid" }, advanced.map((f) => fieldControl(f, obj, ctx))),
      ]),
    );
  }
  return nodes;
}

// ── card builders ────────────────────────────────────────────────────────────
function card(n: number | null, title: string, subtitle: string | null, body: ElChild[]): HTMLElement {
  return el("section", { class: "card" }, [
    el("div", { class: "card-head" }, [
      n ? el("span", { class: "step", text: String(n) }) : null,
      el("div", {}, [el("h2", { text: title }), subtitle ? el("p", { class: "subtitle", text: subtitle }) : null]),
    ]),
    el("div", { class: "card-body" }, body),
  ]);
}

function targetCard(): HTMLElement {
  function choice(value: "python" | "esphome", title: string, desc: string): HTMLElement {
    const active = state.target === value;
    return el(
      "button",
      {
        class: "choice" + (active ? " active" : ""),
        type: "button",
        onclick: () => {
          state.target = value;
          rerenderAll();
        },
      },
      [el("strong", { text: title }), el("span", { text: desc })],
    );
  }
  return card(1, "How will you run AstraMeter?", "Pick where the emulator runs. Not sure? Choose the Home Assistant / Docker option — it's the most common.", [
    el("div", { class: "choice-row" }, [
      choice("python", "Home Assistant add-on, Docker, or a PC", "Generates a config.ini file. AstraMeter runs as software and talks to your power meter over the network."),
      choice("esphome", "On an ESP32 chip (ESPHome)", "Generates an ESPHome YAML file. The emulator runs on a tiny ESP32 board that reads a grid-power sensor."),
    ]),
  ]);
}

function deviceCard(): HTMLElement {
  if (state.target === "esphome") {
    const e = state.esphome;
    return card(2, "Your ESP32 device", "AstraMeter will run on a small ESP32 board you buy and plug in. Tell us which board you have so the file matches it.", [
      el("details", { class: "intro-box", open: true }, [
        el("summary", { text: "First time with ESPHome? Read this" }),
        el("p", { html: "<strong>ESPHome</strong> is free software that turns a tiny, cheap WiFi chip (an <strong>ESP32</strong>) into a smart device by flashing a config file onto it. Here, the ESP32 becomes the power meter your Marstek battery talks to — no PC, Docker, or Home Assistant add-on left running." }),
        el("p", { html: "You'll need to <strong>buy an ESP32 board</strong> (see below), install ESPHome once, paste the file this tool generates, and flash it over USB. Step-by-step instructions appear at the bottom of the page." }),
      ]),
      el("div", { class: "hw" }, [
        el("h3", { text: "🛒 Recommended hardware" }),
        el("p", { class: "help", html: "We recommend the <strong>ESP32-S3 DevKitC-1</strong> — it's cheap, widely available, and is the board this tool defaults to. One board is enough no matter how many batteries you have." }),
        el("ul", { class: "hw-links" }, [
          el("li", {}, [linkOut(HARDWARE.single.url, "Buy 1× " + "ESP32-S3 DevKitC-1"), el("span", { class: "help", text: " — for a single setup" })]),
          el("li", {}, [linkOut(HARDWARE.pack3.url, "Buy 3× ESP32-S3 DevKitC-1"), el("span", { class: "help", text: " — cheaper per board; handy for spares or multiple homes" })]),
        ]),
        el("p", { class: "help affiliate", text: "These are affiliate links — they cost you nothing extra and help support AstraMeter." }),
      ]),
      el("div", { class: "field-grid" }, [
        fieldControl({ key: "name", label: "Device name", help: "Lowercase name used by ESPHome (letters, numbers, hyphens). You can leave the default.", type: "text" }, e, {}),
        fieldControl({ key: "friendlyName", label: "Friendly name", help: "Display name shown in Home Assistant. Optional.", type: "text" }, e, {}),
        fieldControl({ key: "board", label: "ESP32 board", help: "⚠ This MUST match the board you actually bought, or flashing will fail. If you bought the recommended one, leave it as ESP32-S3 DevKitC-1.", type: "select", options: ESP_BOARDS }, e, { structural: true }),
        fieldControl({ key: "ctType", label: "Emulated CT type", help: "HME-4 emulates a CT002; HME-3 emulates a CT003. Match what your Marstek battery expects (CT002 is the common choice).", type: "select", options: [{ value: "HME-4", label: "CT002 (HME-4)" }, { value: "HME-3", label: "CT003 (HME-3)" }] }, e, {}),
      ]),
      el("p", { class: "note", html: "WiFi credentials aren't stored in the file — ESPHome reads them from a separate <code>secrets.yaml</code>. The flashing steps at the bottom show exactly what to put there." }),
    ]);
  }

  // Python: device-type multiselect
  const g = state.general;
  const typeButtons = DEVICE_TYPES.map((d) => {
    const active = g.deviceTypes.includes(d.value);
    return el(
      "button",
      {
        type: "button",
        class: "pill" + (active ? " active" : ""),
        title: d.help,
        onclick: () => {
          if (active) g.deviceTypes = g.deviceTypes.filter((t) => t !== d.value);
          else g.deviceTypes = [...g.deviceTypes, d.value];
          if (g.deviceTypes.length === 0) g.deviceTypes = [d.value];
          rerenderAll();
        },
      },
      d.label,
    );
  });
  // NOTE: `html:` renders as innerHTML. Only interpolate trusted static schema
  // constants here (d.label/d.help) — never user/restored state. g.deviceTypes
  // (user-controlled) is used only as a membership filter, not rendered.
  const selectedHelp = DEVICE_TYPES.filter((d) => g.deviceTypes.includes(d.value)).map((d) => el("li", { html: `<strong>${d.label}:</strong> ${d.help}` }));

  return card(2, "Which meter should AstraMeter pretend to be?", "Your battery talks to a power meter it trusts. AstraMeter impersonates one. One battery → keep Shelly Pro 3EM. Two or more batteries that should share load → choose CT002.", [
    el("div", { class: "pill-row" }, typeButtons),
    el("ul", { class: "pill-help" }, selectedHelp),
    el("details", { class: "adv" }, [
      el("summary", { text: "Advanced general options" }),
      el("div", { class: "field-grid" }, [
        fieldControl({ key: "deviceIds", label: "Device IDs", help: "Optional fixed IDs (comma-separated, same order as the meters above). Leave blank to auto-generate.", type: "text", placeholder: "shellypro3em-c59b15461a21" }, g, {}),
        fieldControl({ key: "skipPowermeterTest", label: "Skip power meter test on startup", help: "Skip the connection check when AstraMeter starts.", type: "checkbox" }, g, {}),
        fieldControl({ key: "webConfigEnabled", label: "Enable built-in web config editor", help: "Opt-in editor at http://<host>:<port>/config.", type: "checkbox" }, g, { structural: true }),
        g.webConfigEnabled ? fieldControl({ key: "webServerPort", label: "Web server port", help: "Default 52500.", type: "number", placeholder: "52500" }, g, {}) : null,
        fieldControl({ key: "throttleInterval", label: "Global throttle interval (s)", help: "Minimum seconds between readings for every meter. 0 = off. You can override per meter below.", type: "number", placeholder: "0" }, g, {}),
        fieldControl({ key: "waitForNextMessage", label: "Wait for fresh push (global)", help: "Wait up to 2s for the newest reading from push-based meters.", type: "select", options: [{ value: "", label: "Default (on)" }, { value: "true", label: "On" }, { value: "false", label: "Off" }] }, g, {}),
        fieldControl({ key: "dedupeTimeWindow", label: "Dedupe window (s)", help: "Ignore repeated requests from the same client within this window. 0 = off.", type: "number", placeholder: "0" }, g, {}),
      ]),
    ]),
  ]);
}

function meterEditor(meter: Meter, index: number): HTMLElement {
  const pm = getPowermeter(meter.type) || POWERMETERS[0];
  const canPhase = PHASE_CAPABLE.has(meter.type);

  const sourceSelect = el(
    "select",
    {
      onchange: (e: Event) => {
        meter.type = (e.target as HTMLInputElement).value;
        meter.fields = {};
        meter.phases = 1;
        rerenderAll();
      },
    },
    POWERMETERS.map((p) => el("option", { value: p.id, ...(p.id === meter.type ? { selected: true } : {}) }, p.label)),
  );

  const badge =
    state.target === "esphome"
      ? esphomeBadge(pm)
      : null;

  const phaseToggle = canPhase
    ? el("div", { class: "field" }, [
        el("label", { class: "field-label", text: "How many phases?" }),
        el(
          "select",
          {
            onchange: (e: Event) => {
              meter.phases = Number((e.target as HTMLInputElement).value);
              rerenderAll();
            },
          },
          [
            el("option", { value: "1", ...(meter.phases !== 3 ? { selected: true } : {}) }, "Single-phase (one value)"),
            el("option", { value: "3", ...(meter.phases === 3 ? { selected: true } : {}) }, "Three-phase (L1 / L2 / L3)"),
          ],
        ),
        el("p", { class: "help", text: "Most homes are single-phase. Pick three-phase only if your meter reports L1/L2/L3 separately." }),
      ])
    : null;

  const removeBtn =
    state.meters.length > 1
      ? el("button", { type: "button", class: "link-danger", onclick: () => { state.meters.splice(index, 1); rerenderAll(); } }, "Remove this meter")
      : null;

  const suffixField =
    state.meters.length > 1
      ? fieldControl({ key: "suffix", label: "Section suffix", help: "Unique label so each meter has its own section, e.g. 1, garage.", type: "text", placeholder: String(index + 1) }, meter, {})
      : null;
  const netmaskField =
    state.meters.length > 1
      ? fieldControl({ key: "netmask", label: "NETMASK (which batteries use this meter)", help: "CIDR of battery IPs that should use this meter, e.g. 192.168.1.0/24.", type: "text", placeholder: "192.168.1.0/24" }, meter, {})
      : null;

  return el("div", { class: "meter" }, [
    el("div", { class: "meter-head" }, [
      el("div", { class: "field grow" }, [el("label", { class: "field-label", text: "Power meter type" }), sourceSelect]),
      badge,
    ]),
    el("p", { class: "blurb", text: pm.blurb }),
    pm.docPython ? el("a", { class: "doclink", href: ghDoc(pm.docPython!), target: "_blank", rel: "noopener" }, "Reference for this meter ↗") : null,
    suffixField,
    phaseToggle,
    el("div", { class: "field-grid" }, fieldGroup(pm.fields, meter.fields, { phases: meter.phases })),
    el("details", { class: "adv" }, [
      el("summary", { text: "Fine-tuning (smoothing, calibration, throttling, PID)" }),
      el("p", { class: "help", text: "All optional. These shape the reading before it reaches your battery." }),
      el("div", { class: "field-grid" }, fieldGroup(PER_METER_TUNING, meter.tuning, { phases: meter.phases })),
    ]),
    netmaskField,
    removeBtn,
  ]);
}

function esphomeBadge(pm: Powermeter): HTMLElement {
  const tier = (pm.esphome && pm.esphome.tier) || "unsupported";
  const map = {
    native: ["Native on ESP32", "ok"],
    generic: ["Works via HTTP poll", "ok"],
    alternate: ["Alternate path needed", "warn"],
    unsupported: ["No ESP32 support yet", "bad"],
  };
  const [text, cls] = map[tier] || map.unsupported;
  const note = pm.esphome && pm.esphome.note ? pm.esphome.note : "";
  return el("span", { class: "badge badge-" + cls, title: note, text });
}

function meterCard(): HTMLElement {
  const meters = state.meters.map((m, i) => meterEditor(m, i));
  const addBtn =
    state.target === "python"
      ? el("button", { type: "button", class: "secondary", onclick: () => { state.meters.push(newMeter("shelly")); rerenderAll(); } }, "+ Add another power meter")
      : null;
  const intro =
    state.target === "esphome"
      ? "On an ESP32 the emulator reads one grid-power sensor. Pick the source below — the badge shows how well each works on ESP32."
      : "Tell us where AstraMeter should read your real grid power. Add more than one only for advanced multi-network setups.";
  return card(3, "Your power meter", intro, [...meters, addBtn]);
}

function ctCard(): HTMLElement | null {
  const showPython = state.target === "python" && (state.general.deviceTypes.includes("ct002") || state.general.deviceTypes.includes("ct003"));
  const show = state.target === "esphome" || showPython;
  if (!show) return null;
  const f = state.ct.fields;
  const group = (title: string, fields: Field[], openByDefault = false): HTMLElement =>
    el("details", { class: "adv", ...(openByDefault ? { open: true } : {}) }, [
      el("summary", { text: title }),
      el("div", { class: "field-grid" }, fields.map((fl) => fieldControl(fl, f, {}))),
    ]);
  return card(4, "Battery steering (CT002 / CT003)", "How AstraMeter steers your battery (or balances several). The defaults work well — open a section only if you want to tune it.", [
    el("div", { class: "field-grid" }, CT_BASIC.map((fl) => fieldControl(fl, f, {}))),
    group("Active control", CT_ACTIVE, true),
    group("Multi-battery balancing", CT_BALANCER),
    group("Efficiency optimization (AC batteries only)", CT_EFFICIENCY),
    group("Saturation handling", CT_SATURATION),
  ]);
}

function extrasCard(): HTMLElement {
  const m = state.marstek;
  const mi = state.mqttInsights;
  const marstekBody = [
    fieldControl({ key: "enabled", label: "Auto-register a managed CT device in the Marstek cloud", help: "Optional. Creates a fake CT in your Marstek account so the app can select it. Credentials are only needed once.", type: "checkbox" }, m, { structural: true }),
  ];
  if (m.enabled) marstekBody.push(el("div", { class: "field-grid" }, MARSTEK_FIELDS.map((fl) => fieldControl(fl, m.fields, {}))));

  const insightsBody = [
    fieldControl({ key: "enabled", label: "Publish internal state to MQTT (Home Assistant discovery)", help: "Optional. Exposes grid power, targets and per-battery state to Home Assistant via MQTT.", type: "checkbox" }, mi, { structural: true }),
  ];
  if (mi.enabled) insightsBody.push(el("div", { class: "field-grid" }, fieldGroup(MQTT_INSIGHTS_FIELDS, mi.fields, {})));

  return card(5, "Optional extras", "Skip this unless you want Marstek-app integration or Home Assistant MQTT insights.", [
    el("h3", { text: "Marstek cloud registration" }),
    ...marstekBody,
    el("hr", {}),
    el("h3", { text: "MQTT Insights / Home Assistant" }),
    ...insightsBody,
  ]);
}

// Shown only for the ESPHome target: a no-prior-knowledge guide to actually
// getting the generated YAML onto the chip.
function esphomeStepsCard(): HTMLElement | null {
  if (state.target !== "esphome") return null;
  const e = state.esphome;
  const li = (html: string) => el("li", { html });
  return card(6, "How to flash this onto your ESP32", "Follow these once. After that, the board runs on its own — you can unplug it from your PC and power it from any USB charger near your battery.", [
    el("ol", { class: "steps" }, [
      li("<strong>Get the board.</strong> Buy an ESP32-S3 DevKitC-1 (links in step 2 above) and plug it into your computer with a USB cable that supports data."),
      li("<strong>Install ESPHome.</strong> Easiest: in Home Assistant, go to <em>Settings → Add-ons → Add-on Store</em> and install <strong>ESPHome Device Builder</strong>. No Home Assistant? Use the web installer at <a href='https://web.esphome.io' target='_blank' rel='noopener'>web.esphome.io</a> (Chrome/Edge), or install the CLI with <code>pip install esphome</code>."),
      li("<strong>Create the device.</strong> In ESPHome click <em>+ New Device</em>, give it a name, and when it generates a starter file, <strong>replace the entire contents</strong> with the file from the preview on this page (use the <em>Download file</em> or <em>Copy</em> button)."),
      li(
        "<strong>Add your WiFi.</strong> ESPHome keeps secrets separately. Open <em>Secrets</em> (or <code>secrets.yaml</code>) and add:<br><code>wifi_ssid: \"YourWiFiName\"</code><br><code>wifi_password: \"YourWiFiPassword\"</code>" +
          (state.marstek && state.marstek.enabled
            ? "<br><code>marstek_password: \"YourMarstekPassword\"</code> (because you enabled Marstek cloud registration)"
            : ""),
      ),
      li("<strong>Check the board matches.</strong> The file uses <code>board: " + escapeHtml(e.board || "esp32-s3-devkitc-1") + "</code>. This must be the board you actually bought — change it in step 2 above if not."),
      li("<strong>Install / flash.</strong> Click <em>Install → Plug into this computer</em> for the first flash (USB). After that you can update it wirelessly over WiFi. Flashing takes a few minutes."),
      li("<strong>Point your battery at it.</strong> In the Marstek app, set the battery to use a CT002/CT003 meter (matching the CT type you chose). The ESP32 answers on your network automatically — power it from any USB charger near the battery."),
    ]),
    el("p", { class: "note", html: "Full reference: <a href='" + ghDoc("README.md#esphome-external-component-run-on-an-esp32") + "' target='_blank' rel='noopener'>ESPHome external component docs ↗</a>. Stuck? The board, WiFi, and CT-type are the three things to double-check." }),
  ]);
}

// ── preview + actions ─────────────────────────────────────────────────────────
function refreshPreview(): void {
  const pre = document.getElementById("preview-code");
  if (!pre) return;
  let text = "";
  try {
    text = generate(state);
  } catch (err) {
    text = "# Error generating config: " + (err as Error).message;
  }
  pre.textContent = text;
  const fn = document.getElementById("preview-filename");
  if (fn) fn.textContent = state.target === "esphome" ? "astrameter.yaml" : "config.ini";
  saveState();
}

function previewPanel(): HTMLElement {
  const filename = state.target === "esphome" ? "astrameter.yaml" : "config.ini";
  return el("aside", { class: "preview", id: "preview" }, [
    el("div", { class: "preview-head" }, [
      el("span", { text: "Live preview — " }),
      el("code", { id: "preview-filename", text: filename }),
    ]),
    el("pre", {}, [el("code", { id: "preview-code" })]),
    el("div", { class: "preview-actions" }, [
      el("button", { type: "button", class: "primary", onclick: copyConfig }, "Copy"),
      el("button", { type: "button", class: "primary", onclick: downloadConfig }, "Download file"),
    ]),
  ]);
}

function safeGenerate(): string | null {
  try {
    return generate(state);
  } catch {
    toast("Couldn't generate the config — check the preview for details", true);
    return null;
  }
}

function copyConfig(): void {
  const text = safeGenerate();
  if (text == null) return;
  navigator.clipboard.writeText(text).then(
    () => toast("Copied to clipboard"),
    () => toast("Copy failed — select the text manually", true),
  );
}

function downloadConfig(): void {
  const text = safeGenerate();
  if (text == null) return;
  const name = state.target === "esphome" ? "astrameter.yaml" : "config.ini";
  downloadText(name, text);
}

function downloadText(filename: string, text: string): void {
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = el("a", { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

// ── project save / load ─────────────────────────────────────────────────────
function saveState(): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {
    /* storage may be unavailable (private mode) */
  }
}

function loadState(): State | null {
  // 1) shared link wins
  try {
    const hash = location.hash.replace(/^#state=/, "");
    if (hash) {
      const decoded = safeParse(decodeURIComponent(escape(atob(hash))));
      history.replaceState(null, "", location.pathname + location.search);
      return migrate(decoded);
    }
  } catch {
    /* ignore bad hash */
  }
  // 2) localStorage
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return migrate(safeParse(raw));
  } catch {
    /* ignore */
  }
  return null;
}

function saveProject(): void {
  downloadText("astrameter-project.json", JSON.stringify(state, null, 2));
}

function loadProject(file: File): void {
  const reader = new FileReader();
  reader.onload = () => {
    try {
      state = migrate(safeParse(reader.result as string));
      rerenderAll();
      toast("Project loaded");
    } catch {
      toast("Could not read that file", true);
    }
  };
  reader.readAsText(file);
}

function shareLink(): void {
  try {
    const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(state))));
    const url = location.origin + location.pathname + "#state=" + encoded;
    navigator.clipboard.writeText(url).then(
      () => toast("Share link copied to clipboard"),
      () => prompt("Copy this link:", url),
    );
  } catch {
    toast("Could not build share link", true);
  }
}

function resetProject(): void {
  if (!confirm("Start over? This clears everything you've entered.")) return;
  state = defaultState();
  rerenderAll();
}

function toast(msg: string, isError = false): void {
  const t = el("div", { class: "toast" + (isError ? " toast-error" : ""), text: msg });
  document.body.appendChild(t);
  requestAnimationFrame(() => t.classList.add("show"));
  setTimeout(() => {
    t.classList.remove("show");
    setTimeout(() => t.remove(), 300);
  }, 2200);
}

// ── render ───────────────────────────────────────────────────────────────────
function rerenderAll(): void {
  const form = document.getElementById("form-col")!;
  form.innerHTML = "";
  form.append(targetCard(), deviceCard(), meterCard());
  const ct = ctCard();
  if (ct) form.append(ct);
  form.append(extrasCard());
  const steps = esphomeStepsCard();
  if (steps) form.append(steps);
  form.append(projectCard());
  refreshPreview();
}

function projectCard(): HTMLElement {
  const fileInput = el("input", { type: "file", accept: "application/json", class: "hidden", onchange: (e: Event) => { const f = (e.target as HTMLInputElement).files?.[0]; if (f) loadProject(f); } });
  return card(null, "Save your work", "Your answers are saved in this browser automatically. You can also export a project file to back up or continue on another device.", [
    el("div", { class: "btn-row" }, [
      el("button", { type: "button", class: "secondary", onclick: saveProject }, "💾 Save project file"),
      el("button", { type: "button", class: "secondary", onclick: () => fileInput.click() }, "📂 Load project file"),
      el("button", { type: "button", class: "secondary", onclick: shareLink }, "🔗 Copy share link"),
      el("button", { type: "button", class: "link-danger", onclick: resetProject }, "Start over"),
      fileInput,
    ]),
  ]);
}

function boot(): void {
  const root = document.getElementById("app")!;
  root.append(el("div", { class: "layout" }, [el("div", { id: "form-col", class: "form-col" }), previewPanel()]));
  rerenderAll();
}

document.addEventListener("DOMContentLoaded", boot);
