"""Moving between add-on options and a hand-written ``config.ini``.

In add-on options mode the running ``config.ini`` is a build artifact that
``run.sh`` regenerates on every container start.  Switching to file mode
therefore has to *materialize* that generated file into the add-on's shared
config directory first, so the user starts from the configuration that is
actually running instead of an empty file.
"""

from __future__ import annotations

import os
import shutil

from astrameter.config.logger import logger

# Where the Supervisor mounts the add-on's own writable config directory.
# `custom_config` is resolved relative to this by run.sh.
ADDON_CONFIG_DIR = "/config"

_BANNER = """\
# Generated by AstraMeter from the add-on options.
#
# The add-on's `custom_config` option now points at this file, so the
# options in the add-on UI are no longer used — edit this file instead.
# Delete the `custom_config` option to go back to the guided setup.
"""


def target_path(filename: str, config_dir: str = ADDON_CONFIG_DIR) -> str:
    """Absolute path for a ``custom_config`` filename, rejecting traversal."""
    safe = os.path.basename(filename.strip())
    if not safe or safe.startswith("."):
        raise ValueError(f"Invalid config filename: {filename!r}")
    return os.path.join(config_dir, safe)


def materialize_config(
    source_path: str | None,
    filename: str,
    config_dir: str = ADDON_CONFIG_DIR,
) -> str:
    """Copy the running config to *filename* in the add-on config dir.

    Returns the written path.  An existing file is never overwritten — the
    user may already have a config there worth keeping, and silently
    clobbering it would be unrecoverable.
    """
    destination = target_path(filename, config_dir)
    if os.path.exists(destination):
        logger.info("Config file %s already exists; leaving it as-is", destination)
        return destination
    os.makedirs(config_dir, exist_ok=True)
    if source_path and os.path.exists(source_path):
        shutil.copyfile(source_path, destination)
        with open(destination, encoding="utf-8") as handle:
            body = handle.read()
        with open(destination, "w", encoding="utf-8") as handle:
            handle.write(_BANNER + "\n" + body)
    else:
        with open(destination, "w", encoding="utf-8") as handle:
            handle.write(_BANNER)
    logger.info("Materialized running configuration to %s", destination)
    return destination
